---
apiVersion: v2
name: safe-config
version: 0.1.2
appVersion: v2.59.0
description: A Helm chart for configuration service
type: application
icon: "https://raw.githubusercontent.com/safe-global/safe-core-sdk/main/assets/logo.png"
